image:
  repository: misha6sharma/react-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  enabled: true
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
serviceAccount:
  create: true
  name: my-app
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
