name: Ansible React Deployment
#Git actions is triggering me more than the workflow ya
on:
  workflow_run:
    workflows: ["Terraform CI/CD"]  
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem

            - name: Download EC2 IP artifact
        uses: actions/download-artifact@v3
        with:
          name: ec2-ip

      - name: Read IP into env
        run: |
          EC2_PUBLIC_IP=$(cat ec2_ip.txt)
          echo "EC2_PUBLIC_IP=$EC2_PUBLIC_IP" >> $GITHUB_ENV

      - name: Create Ansible inventory
        run: |
         echo "[web]" > inventory.ini
         echo "${EC2_PUBLIC_IP} ansible_user=ubuntu ansible_ssh_private_key_file=key.pem" >> inventory.ini
         cat inventory.ini


      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i inventory.ini ansible/react_app.yaml

