name: Deploy React App to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy to ECS
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: latest
      ECR_REPO: react-app_repo
      AWS_REGION: ap-south-1

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js (for caching and optional frontend builds)
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Docker image
      run: |
        docker build -t $ECR_REPO ./aws-devops-handson1/aws-devops-handson
        docker tag $ECR_REPO:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/$ECR_REPO:${{ env.IMAGE_TAG }}

    - name: Push image to ECR
      run: |
        docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/$ECR_REPO:${{ env.IMAGE_TAG }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: |
        cd terraform_ecs
        terraform init

    - name: Terraform Apply
      run: |
        cd terraform_ecs
        terraform apply -auto-approve
      