name: Terraform CI/CD
# This workflow runs Terraform commands on pushes to the main branch.
on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: "Terraform Plan and Apply"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.6

    - name: Terraform Init
      run: cd terraform && terraform init

    - name: Terraform Validate
      run: cd terraform && terraform validate

    - name: Terraform Plan
      run: cd terraform &&  terraform plan 


    - name: Terraform Apply
      run: cd terraform && terraform apply -auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
